[build]
  command = "npm run build"
  publish = "dist/client"

  # Don't trigger a build of this site if the code commits were in a different part of the monorepo
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[dev]
  command = "npm run dev"

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

# These are only used to set up the template, and are not used in the build
# If you want to update the real values, change them in the site UI or CLI
[template.environment]
PUBLIC_STORE_DOMAIN = "Store domain - set this to 'mock.shop' to try the demo site"
SESSION_SECRET = "Session secret - set this to a random value for production"
