CREATE TABLE
  pets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    greeting TEXT NOT NULL,
    bio TEXT NOT NULL,
    image TEXT NOT NULL,
    snuggles INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  );
